# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appId', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobId', models.CharField(max_length=25)),
                ('jobName', models.CharField(max_length=50)),
                ('requirement', models.TextField()),
                ('timeStamp', models.DateTimeField()),
                ('numOfPositions', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginId', models.CharField(max_length=10)),
                ('userName', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectId', models.CharField(max_length=25)),
                ('projectName', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=25)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=50)),
                ('areaOfInterest', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=20)),
                ('emailId', models.EmailField(max_length=50)),
                ('resumeDoc', models.FileField(default='NYUTeamUp/teamupapp/storage/', upload_to='NYUTeamUp/teamupapp/storage/')),
                ('loginId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamupapp.Login')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamupapp.User'),
        ),
        migrations.AddField(
            model_name='job',
            name='projectId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamupapp.Project'),
        ),
        migrations.AddField(
            model_name='application',
            name='jobId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamupapp.Job'),
        ),
        migrations.AddField(
            model_name='application',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamupapp.User'),
        ),
    ]
